// js/content/shop/essentials/grocery.js – Grocery & Essentials Items
// Basic consumables: food, drink, and daily necessities.

export const groceryItems = [
  // ----- FOOD ITEMS -----
  {
    id: 'cheap_meal',
    name: 'Cheap Meal',
    desc: 'Restores 30 hunger. Consecutive use causes malnutrition debuff.',
    icon: '🍜',
    price: 5,
    category: 'Essentials',
    effectType: 'hunger',
    value: 30,
    permanent: false,
  },
  {
    id: 'restaurant_meal',
    name: 'Restaurant Meal',
    desc: 'Restores 60 hunger and +10 morale. Psychological boost.',
    icon: '🥩',
    price: 18,
    category: 'Essentials',
    effectType: 'hunger_morale',
    value: 60,
    moraleBoost: 10,
    permanent: false,
  },

  // ----- DRINK ITEMS -----
  {
    id: 'coffee',
    name: 'Coffee',
    desc: '+15 energy now. Energy crash -5 next day.',
    icon: '☕',
    price: 2,
    category: 'Essentials',
    effectType: 'energy',
    value: 15,
    caffeineDays: 5,
    permanent: false,
  },
  {
    id: 'energy_drink',
    name: 'Energy Drink',
    desc: '+25 energy now. Energy crash -8 next day.',
    icon: '⚡',
    price: 3,
    category: 'Essentials',
    effectType: 'energy',
    value: 25,
    caffeineDays: 8,
    permanent: false,
  },

  // ----- BASIC ITEMS -----
  {
    id: 'water_bottle',
    name: 'Water Bottle',
    desc: '+10 energy, +5 hunger. Stay hydrated.',
    icon: '💧',
    price: 1,
    category: 'Essentials',
    effectType: 'energy',
    value: 10,
    permanent: false,
  },
  {
    id: 'snack',
    name: 'Snack Bar',
    desc: '+15 hunger, cheap and quick.',
    icon: '🍫',
    price: 2,
    category: 'Essentials',
    effectType: 'hunger',
    value: 15,
    permanent: false,
  },
  {
    id: 'bread',
    name: 'Loaf of Bread',
    desc: '+40 hunger. A staple.',
    icon: '🍞',
    price: 4,
    category: 'Essentials',
    effectType: 'hunger',
    value: 40,
    permanent: false,
  },

  // ----- HEALTH & WELLNESS (also in essentials) -----
  {
    id: 'medicine',
    name: 'Medicine',
    desc: '+20 health. Essential for recovery.',
    icon: '💊',
    price: 8,
    category: 'Essentials',
    effectType: 'health',
    value: 20,
    permanent: false,
  },
  {
    id: 'first_aid',
    name: 'First Aid Kit',
    desc: '+30 health. Stronger than basic medicine.',
    icon: '🩹',
    price: 15,
    category: 'Essentials',
    effectType: 'health',
    value: 30,
    permanent: false,
  },

  // ----- SERVICES (one-time) -----
  {
    id: 'gym_session',
    name: 'Gym Session',
    desc: '+15 health, +10 morale, -10 stress. Stay fit.',
    icon: '🏋️',
    price: 15,
    category: 'Essentials',
    effectType: 'gym',
    permanent: false,
  },
  {
    id: 'therapy',
    name: 'Therapy Session',
    desc: '-30 stress, +20 morale. Emergency mental reset.',
    icon: '🧠',
    price: 40,
    category: 'Essentials',
    effectType: 'therapy',
    permanent: false,
  },
  {
  id: 'phone',
  name: 'Smartphone',
  desc: 'A basic smartphone. Required for delivery jobs.',
  icon: '📱',
  price: 100,
  category: 'Essentials',
  effectType: 'inventory',
  inventoryId: 'phone',
  permanent: true,
  },
  {
  id: 'shower',
  name: 'Shower',
  desc: '15 min shower. +40 hygiene, minor fatigue refresh.',
  icon: '🚿',
  price: 0,
  category: 'Services',
  effectType: 'shower',
  permanent: false,
},
];