export const apparelItems = [
  {
    id: 'suit',
    name: 'Tailored Suit',
    desc: 'Required for office jobs. High social status.',
    icon: '👔',
    price: 450.00,
    category: 'Apparel',
    effectType: 'inventory',
    inventoryId: 'suit',
    weightKg: 1.0,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: true,
  },
  {
    id: 'cologne',
    name: 'Premium Cologne',
    desc: 'Overrides low hygiene penalty for 12 hours.',
    icon: '✨',
    price: 65.00,
    category: 'Apparel',
    effectType: 'cologne',
    buffDuration: 12,
    weightKg: 0.2,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: false,
  },
];