export const bakeryItems = [
  {
    id: 'sourdough_loaf',
    name: 'Sourdough Loaf',
    desc: 'Artisanal bread. Restores 40 hunger. Spoils in 3 days.',
    icon: '🍞',
    price: 5.50,
    category: 'Food',
    effectType: 'hunger',
    value: 40,
    weightKg: 0.4,
    isPerishable: true,
    shelfLifeDays: 3,
    permanent: false,
  },
  {
    id: 'croissant',
    name: 'Butter Croissant',
    desc: 'Flaky pastry. Restores 20 hunger, +5 morale. Spoils in 2 days.',
    icon: '🥐',
    price: 3.50,
    category: 'Food',
    effectType: 'hunger_morale',
    value: 20,
    moraleBoost: 5,
    weightKg: 0.15,
    isPerishable: true,
    shelfLifeDays: 2,
    permanent: false,
  },
];