export const butcherItems = [
  {
    id: 'chicken_breast',
    name: 'Chicken Breast (1 lb)',
    desc: 'Low fat, high protein. Requires cooking. Restores 50 hunger when cooked.',
    icon: '🍗',
    price: 4.50,
    category: 'Food',
    effectType: 'raw_meat',      // needs cooking
    value: 50,
    weightKg: 0.5,
    isPerishable: true,
    shelfLifeDays: 2,
    permanent: false,
  },
  {
    id: 'ground_beef',
    name: 'Ground Beef 80/20 (1 lb)',
    desc: 'Cheap protein. Greasy. Cooked restores 45 hunger but adds 5 stress.',
    icon: '🥩',
    price: 6.00,
    category: 'Food',
    effectType: 'raw_meat',
    value: 45,
    stressGain: 5,
    weightKg: 0.5,
    isPerishable: true,
    shelfLifeDays: 2,
    permanent: false,
  },
  {
    id: 'ribeye_steak',
    name: 'Premium Ribeye Steak (1 lb)',
    desc: 'High-end luxury meat. Cooked restores 70 hunger, +10 morale.',
    icon: '🥩',
    price: 18.00,
    category: 'Food',
    effectType: 'raw_meat',
    value: 70,
    moraleBoost: 10,
    weightKg: 0.5,
    isPerishable: true,
    shelfLifeDays: 3,
    permanent: false,
  },
];