export const greengrocerItems = [
  {
    id: 'bananas',
    name: 'Bunch of Bananas',
    desc: 'Quick, no-prep food. Removes malnutrition debuff.',
    icon: '🍌',
    price: 2.50,
    category: 'Food',
    effectType: 'cure_malnutrition',
    hungerValue: 15,
    weightKg: 0.3,
    isPerishable: true,
    shelfLifeDays: 4,
    permanent: false,
  },
  {
    id: 'avocados',
    name: 'Bag of Avocados',
    desc: 'Healthy fats. Slows hunger decay by 15% for 6 hours.',
    icon: '🥑',
    price: 5.00,
    category: 'Food',
    effectType: 'metabolic_boost',
    hungerValue: 20,
    buffDuration: 6,   // hours
    weightKg: 0.4,
    isPerishable: true,
    shelfLifeDays: 3,
    permanent: false,
  },
  {
    id: 'spinach',
    name: 'Fresh Organic Spinach',
    desc: 'Boosts health regeneration. +10 health.',
    icon: '🥬',
    price: 3.00,
    category: 'Food',
    effectType: 'health',
    value: 10,
    weightKg: 0.2,
    isPerishable: true,
    shelfLifeDays: 3,
    permanent: false,
  },
];