export const pharmacyItems = [
  {
    id: 'painkillers',
    name: 'Generic Painkillers',
    desc: 'Cures minor health issues. +20 health.',
    icon: '💊',
    price: 6.00,
    category: 'Health',
    effectType: 'health',
    value: 20,
    weightKg: 0.05,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: false,
  },
  {
    id: 'antibiotics',
    name: 'Broad-Spectrum Antibiotics',
    desc: 'Cures infections from low hygiene or brawls. +40 health, removes infection debuff.',
    icon: '💉',
    price: 50.00,
    category: 'Health',
    effectType: 'antibiotics',
    healthValue: 40,
    weightKg: 0.1,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: false,
  },
  {
    id: 'sleep_aid',
    name: 'Prescription Sleep Aid',
    desc: 'Forces a deep 9‑hour sleep, fully restores fatigue.',
    icon: '😴',
    price: 35.00,
    category: 'Health',
    effectType: 'sleep_aid',
    weightKg: 0.05,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: false,
  },
];