export const techItems = [
  {
    id: 'phone_budget',
    name: 'Pear Phone Lite',
    desc: 'Budget smartphone. Unlocks delivery jobs. Slow data, low durability.',
    icon: '📱',
    price: 120.00,
    category: 'Electronics',
    effectType: 'inventory',
    inventoryId: 'phone',
    weightKg: 0.2,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: true,
    durability: 80,       // lower durability
  },
  {
    id: 'phone_flagship',
    name: 'Horizon iX Ultra',
    desc: 'Flagship phone. Boosts social status, speeds up online scams.',
    icon: '📱',
    price: 1199.00,
    category: 'Electronics',
    effectType: 'inventory',
    inventoryId: 'phone',
    weightKg: 0.25,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: true,
    durability: 120,      // higher durability
  },
  {
    id: 'laptop_budget',
    name: 'Budget Chromebook',
    desc: 'Basic laptop for studying. Slow, can’t run trading software.',
    icon: '💻',
    price: 200.00,
    category: 'Electronics',
    effectType: 'inventory',
    inventoryId: 'laptop',
    weightKg: 1.5,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: true,
    durability: 70,
  },
  {
    id: 'laptop_workstation',
    name: 'Custom Workstation Laptop',
    desc: 'High‑end laptop for trading. Eliminates latency on trading floor.',
    icon: '💻',
    price: 2400.00,
    category: 'Electronics',
    effectType: 'inventory',
    inventoryId: 'laptop',
    weightKg: 2.0,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: true,
    durability: 150,
  },
  {
    id: 'tools',
    name: 'Basic Toolset',
    desc: 'For repairs. Can fix your own appliances or laptop.',
    icon: '🔧',
    price: 45.00,
    category: 'Gear',
    effectType: 'inventory',
    inventoryId: 'tools',
    weightKg: 2.0,
    isPerishable: false,
    shelfLifeDays: 0,
    permanent: true,
    durability: 100, // tools don't degrade
    },
];