// js/content/courses/life.js – Life Skills & Personal Finance Courses
// Courses that teach budgeting, negotiation, credit, and investing.

export const lifeCourses = [
  {
    id: 'budgeting',
    title: 'Personal Budgeting',
    desc: 'Control spending, save more, understand cash flow. Build a budget that works for you.',
    icon: '💰',
    xpReward: 15,
    category: 'life',
    skillUnlock: 'budgeting',
    url: 'https://www.youtube.com/results?search_query=personal+budgeting+tips',
  },
  {
    id: 'negotiation',
    title: 'Negotiation Skills',
    desc: 'Learn to negotiate salary, prices, and deals. Get more value in every conversation.',
    icon: '🤝',
    xpReward: 20,
    category: 'life',
    skillUnlock: 'negotiation',
    url: 'https://www.youtube.com/results?search_query=negotiation+skills',
  },
  {
    id: 'credit_scores',
    title: 'Credit & Loans',
    desc: 'Understand credit scores, how they work, loan types, interest rates, and how to improve your score.',
    icon: '🏦',
    xpReward: 20,
    category: 'life',
    skillUnlock: 'credit_scores',
    url: 'https://www.youtube.com/results?search_query=understanding+credit+score',
  },
  {
    id: 'passive_investing',
    title: 'Passive Investing',
    desc: 'Index funds, ETFs, compound interest, long-term wealth building for financial freedom.',
    icon: '🌱',
    xpReward: 30,
    category: 'life',
    skillUnlock: 'investing',
    url: 'https://www.youtube.com/results?search_query=passive+investing+index+funds',
  },
  {
    id: 'real_estate',
    title: 'Real Estate Basics',
    desc: 'Learn about property investing, mortgages, rental income, and building wealth through real estate.',
    icon: '🏠',
    xpReward: 35,
    category: 'life',
    skillUnlock: 'real_estate',
    url: 'https://www.youtube.com/results?search_query=real+estate+investing+basics',
  },
  {
    id: 'entrepreneurship',
    title: 'Entrepreneurship 101',
    desc: 'Start and run a business, manage cash flow, marketing, and scale your venture.',
    icon: '🚀',
    xpReward: 40,
    category: 'life',
    skillUnlock: 'entrepreneurship',
    url: 'https://www.youtube.com/results?search_query=entrepreneurship+basics',
  },
];