// js/content/courses/trading.js – Trading & Financial Courses
// Courses that teach trading, analysis, and risk management.

export const tradingCourses = [
  {
    id: 'trading_basics',
    title: 'Trading 101: Markets & Charts',
    desc: 'How markets work, price action, basic chart reading. The foundation of all trading.',
    icon: '📊',
    xpReward: 25,
    category: 'trading',
    skillUnlock: 'trading_basics',
    url: 'https://www.youtube.com/results?search_query=stock+market+basics+beginners',
  },
  {
    id: 'candlesticks',
    title: 'Candlestick Patterns',
    desc: 'Learn to read candles and predict price direction with common patterns like doji, hammer, and engulfing.',
    icon: '🕯️',
    xpReward: 30,
    category: 'trading',
    skillUnlock: 'candlesticks',
    url: 'https://www.youtube.com/results?search_query=candlestick+patterns+trading',
  },
  {
    id: 'technical_analysis',
    title: 'Technical Analysis Mastery',
    desc: 'Support & resistance, trend lines, RSI, MACD, moving averages. Essential tools for any trader.',
    icon: '📉',
    xpReward: 40,
    category: 'trading',
    skillUnlock: 'technical_analysis',
    url: 'https://www.youtube.com/results?search_query=technical+analysis+beginners',
  },
  {
    id: 'financial_analysis',
    title: 'Fundamental Analysis',
    desc: 'Read balance sheets, P/E ratios, earnings reports. Understand what makes a company valuable.',
    icon: '📄',
    xpReward: 50,
    category: 'trading',
    skillUnlock: 'financial_analysis',
    url: 'https://www.youtube.com/results?search_query=fundamental+analysis+stock+market',
  },
  {
    id: 'risk_management',
    title: 'Risk Management for Traders',
    desc: 'Position sizing, stop losses, risk/reward ratios, protecting capital from big losses.',
    icon: '🛡️',
    xpReward: 35,
    category: 'trading',
    skillUnlock: 'risk_management',
    url: 'https://www.youtube.com/results?search_query=risk+management+trading',
  },
  {
    id: 'forex_mastery',
    title: 'Forex Trading Mastery',
    desc: 'Currency pairs, pips, leverage, margin, and understanding the global forex market.',
    icon: '💱',
    xpReward: 45,
    category: 'trading',
    skillUnlock: 'forex_mastery',
    url: 'https://www.youtube.com/results?search_query=forex+trading+beginners',
  },
  {
    id: 'advanced_analysis',
    title: 'Advanced Technical Analysis',
    desc: 'Elliot Wave, Fibonacci retracements, Ichimoku clouds. For serious traders.',
    icon: '📈',
    xpReward: 55,
    category: 'trading',
    skillUnlock: 'advanced_analysis',
    url: 'https://www.youtube.com/results?search_query=advanced+technical+analysis',
  },
];